name: Publish Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: write-all      

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest setuptools wheel twine setuptools_scm python-semantic-release

      - name: Run tests
        run: pytest tests/

  publish:
    runs-on: ubuntu-latest
    needs: test  # Ensure tests pass before publishing

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine setuptools_scm python-semantic-release

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Update changelog and publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.OURTASK_TASK_API_TOKEN }}
        run: |
          semantic-release version --changelog
          twine upload dist/*
